export const WORDS = [
	'Cat (Кот)',
	'Dog (Собака)',
	'Sun (Солнце)',
	'Rain (Дождь)',
	'Tree (Дерево)',
	'House (Дом)',
	'Car (Автомобиль)',
	'Happy (Счастливый)',
	'Fast (Быстрый)',
	'Small (Маленький)',
	'Big (Большой)',
	'Jump (Прыгать)',
	'Run (Бегать)',
	'Laugh (Смеяться)',
	'Cry (Плакать)',
	'Flower (Цветок)',
	'Mountain (Гора)',
	'Ocean (Океан)',
	'Explore (Исследовать)',
	'Adventure (Приключение)',
	'Beautiful (Красивый)',
	'Challenge (Испытание)',
	'Curiosity (Любопытство)',
	'Innovation (Инновация)',
	'Resilience (Устойчивость)',
	'Conscientious (Добросовестный)',
	'Perseverance (Упорство)',
	'Collaboration (Сотрудничество)',
	'Extravagant (Экстравагантный)',
	'Incomprehensible (Непонятный)',
];
export const KEYBOARD_LETTERS = Array.from('ABCDEFGHIJKLMNOPQRSTUVWXYZ');
